### ISSUE TITLE
ENVIRONEMNT_ID does not include branch name

### ISSUE THREAD

**Issue by pixelass** [contentful/contentful-action#20]
Reading through the source code the `ENVIRONMENT_ID` should include the branch name.

source: https://github.com/contentful/contentful-action/blob/main/index.js#L44-L66

**Expected Behavior:**

`GH-my-branch-name`

**Actual Behavior:**

`GH-merge`

**Context**

```
Running with the following configuration
Running on feature branch
ENVIRONMENT_ID: GH-merge
Checking for existing versions of environment: GH-merge
Environment not found
Creating environment GH-merge
```

**workflow/action** 

```
      - uses: contentful/contentful-action@v1
        env:
          SPACE_ID: ${{ secrets.SPACE_ID }}
          MANAGEMENT_API_KEY: ${{ secrets.MANAGEMENT_API_KEY }}

```

I also looked through https://github.com/contentful-labs/contentful-action-example but found no hints to faulty usage from our side.
